"""add messages table

Revision ID: 66d0b9505c7b
Revises: 
Create Date: 2026-04-27 17:10:12.171202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66d0b9505c7b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='消息ID'),
    sa.Column('conversation_id', sa.String(length=36), nullable=False, comment='所属会话UUID'),
    sa.Column('role', sa.String(length=20), nullable=False, comment='消息角色: user/assistant/system'),
    sa.Column('content', sa.Text(), nullable=False, comment='消息内容'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.conversation_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='用户聊天记录表'
    )
    op.drop_index(op.f('idx_conversations_conversation_id'), table_name='conversations')
    op.drop_index(op.f('idx_conversations_user_id'), table_name='conversations')
    op.drop_index(op.f('idx_users_email'), table_name='users')
    op.drop_index(op.f('idx_users_username'), table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_users_username'), 'users', ['username'], unique=False)
    op.create_index(op.f('idx_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('idx_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    op.create_index(op.f('idx_conversations_conversation_id'), 'conversations', ['conversation_id'], unique=False)
    op.drop_table('messages')
    # ### end Alembic commands ###
