"""add user_profiles and user_memories tables

Revision ID: 7dc9f3fcdbe3
Revises: 66d0b9505c7b
Create Date: 2026-04-27 23:28:46.717022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = '7dc9f3fcdbe3'
down_revision: Union[str, Sequence[str], None] = '66d0b9505c7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION IF NOT EXISTS vector')
    op.create_table('user_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('learning_level', sa.String(length=50), nullable=True),
    sa.Column('learning_goals', sa.Text(), nullable=True),
    sa.Column('preferred_style', sa.String(length=50), nullable=True),
    sa.Column('known_background', sa.Text(), nullable=True),
    sa.Column('constraints', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('user_memories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('memory_type', sa.String(length=50), nullable=False),
    sa.Column('embedding', Vector(1536), nullable=True),
    sa.Column('source_message_id', sa.Integer(), nullable=True),
    sa.Column('importance', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_message_id'], ['messages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_memories_user_active', 'user_memories', ['user_id', 'is_active'], unique=False)
    op.execute(
        "CREATE INDEX ix_user_memories_embedding ON user_memories "
        "USING hnsw (embedding vector_cosine_ops)"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_user_memories_embedding", table_name="user_memories")
    op.drop_index('ix_user_memories_user_active', table_name='user_memories')
    op.drop_table('user_memories')
    op.drop_table('user_profiles')
    # ### end Alembic commands ###
